import type { Claim } from './types';

export const sampleClaims: Omit<
  Claim,
  'status' | 'error_type' | 'error_explanation' | 'recommended_action' | 'raw_errors'
>[] = [
  {
    claim_id: 'CLM001',
    encounter_type: 'Outpatient',
    service_date: '2024-05-01',
    national_id: 'NATL001',
    member_id: 'MEMB001',
    facility_id: '96GUDLMT',
    unique_id: 'NATL-MEMB-DLMT',
    diagnosis_codes: 'E11.9',
    service_code: 'SRV2007',
    paid_amount_aed: 150,
  },
  {
    claim_id: 'CLM002',
    encounter_type: 'Inpatient',
    service_date: '2024-05-02',
    national_id: 'NATL002',
    member_id: 'MEMB002',
    facility_id: '96GUDLMT',
    unique_id: 'NATL-MEMB-DLMT',
    diagnosis_codes: 'R07.9',
    service_code: 'SRV2001',
    paid_amount_aed: 200,
    approval_number: 'AP1234',
  },
  {
    claim_id: 'CLM003',
    encounter_type: 'Outpatient',
    service_date: '2024-05-03',
    national_id: 'NATL003',
    member_id: 'MEMB003',
    facility_id: '9V7HTI6E',
    unique_id: 'natl-memb-ti6e',
    diagnosis_codes: 'J45.909',
    service_code: 'SRV2006',
    paid_amount_aed: 300,
  },
  {
    claim_id: 'CLM004',
    encounter_type: 'Outpatient',
    service_date: '2024-05-04',
    national_id: 'NATL004',
    member_id: 'MEMB004',
    facility_id: 'M1XCZVQD',
    unique_id: 'NATL-MEMB-ZVQD',
    diagnosis_codes: 'R51,G43.9',
    service_code: 'SRV2001',
    paid_amount_aed: 100,
  },
  {
    claim_id: 'CLM005',
    encounter_type: 'Inpatient',
    service_date: '2024-05-05',
    national_id: 'NATL005',
    member_id: 'MEMB005',
    facility_id: '0DBYE6KP',
    unique_id: 'NATL-MEMB-E6KP',
    diagnosis_codes: 'N18.9',
    service_code: 'SRV1003',
    paid_amount_aed: 1200,
  },
  {
    claim_id: 'CLM006',
    encounter_type: 'Outpatient',
    service_date: '2024-05-06',
    national_id: 'NATL006',
    member_id: 'MEMB006',
    facility_id: '7R1VMIGX',
    unique_id: 'NATL-MEMB-MIGX',
    diagnosis_codes: 'I25.10',
    service_code: 'SRV1001',
    paid_amount_aed: 5000,
  },
   {
    claim_id: 'CLM007',
    encounter_type: 'Outpatient',
    service_date: '2024-05-07',
    national_id: 'NATL007',
    member_id: 'MEMB007',
    facility_id: '2XKSZK4T',
    unique_id: 'NATL-MEMB-ZK4T',
    diagnosis_codes: 'Z34.0',
    service_code: 'SRV2008',
    paid_amount_aed: 450,
    approval_number: 'AP5678'
  },
  {
    claim_id: 'CLM008',
    encounter_type: 'Inpatient',
    service_date: '2024-05-08',
    national_id: 'NATL008',
    member_id: 'MEMB008',
    facility_id: '96GUDLMT',
    unique_id: 'NATL-MEMB-DLMT',
    diagnosis_codes: 'E11.9,R73.03',
    service_code: 'SRV2007',
    paid_amount_aed: 180,
    approval_number: 'AP9101'
  },
  {
    claim_id: 'CLM009',
    encounter_type: 'Outpatient',
    service_date: '2024-05-09',
    national_id: 'NATL009',
    member_id: 'memb009',
    facility_id: '96GUDLMT',
    unique_id: 'NATL-memb-DLMT',
    diagnosis_codes: 'R07.9',
    service_code: 'SRV2001',
    paid_amount_aed: 90,
  },
  {
    claim_id: 'CLM010',
    encounter_type: 'Outpatient',
    service_date: '2024-05-10',
    national_id: 'NATL010',
    member_id: 'MEMB010',
    facility_id: '96GUDLMT',
    unique_id: 'NATL-MEMB-DLMT',
    diagnosis_codes: 'R07.9',
    service_code: 'SRV2001',
    paid_amount_aed: 260,
  }
];
